export {Header} from "./header";
export {BurgerMenu} from "./burger-menu";
export {DeveloperLink} from "./developer-link";
export {Actor} from "./actor-cast/actor";
export {ArrowTop} from "./arrow-top";
export {Loader} from "./loader";
export {Cast} from "./actor-cast/cast";
export {BtnLoader} from "./loader-btn";
export {Card} from "./cards/newly-movie";
export {EasterEgg} from "./easter-egg";
export {SearchCard} from "./cards/search-actor";
export {Card as SearchMovie} from "./cards/search-movie";
